name: RAMClustR
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base
  - r-biocmanager
  - r-interpretmsspectrum
  - bioconductor-msnbase
  - r-rcurl
  - r-dynamictreecut
  - r-e1071
  - r-fastcluster
  - r-ff
  - r-ggplot2
  - r-gplots
  - r-httr
  - r-jsonlite
  - bioconductor-pcamethods
  - bioconductor-preprocesscore
  - r-stringi
  - r-stringr
  - r-webchem
  - r-xml2
  - bioconductor-xcms